In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv('HR_CLEAN_DATA.csv')
df.head(3)

,Employee_Number,Age,Age_Group,Attrition,Business_Travel,Daily_Rate,Distance_From_Home,Education,Education_Field,Environment_Satisfaction,Gender,Hourly_Rate,Job_Involvement,Job_Level,Job_Role,Job_Satisfaction,Marital_Status,Monthly_Income,Monthly_Rate,Num_Companies_Worked,Over_18,Over_Time,Percent_Salary_Hike,Performance_Rating,Relationship_Satisfaction,Standard_Hours,Stock_Option_Level,Total_Working_Years,Training_Times_Last_Year,Work_Life_Balance,Years_At_Company,Years_Since_Last_Promotion,Years_With_Curr_Manager,Date_Birth,Remote_Work
0,162,51,NaN,False,NaN,684.0,6,3,NaN,1,M,51,3,5,Research Director,3,NaN,19537.0,6462.0,7,Y,False,13,3,3,NaN,0,99999,5,3,20,15,15,1972,True
1,259,52,NaN,False,NaN,699.0,1,4,Life Sciences,3,M,65,2,5,Manager,3,NaN,19999.0,5678.0,0,NaN,NaN,14,3,1,NaN,1,34,5,3,33,11,9,1971,True
2,319,42,NaN,False,Travel_Rarely,532.0,4,2,Technical Degree,3,M,58,3,5,Manager,4,Married,19232.0,4933.0,1,NaN,False,11,3,4,NaN,0,22,3,99999,22,11,15,1981,True

In [4]:
valores_unicos_Monthly_Income = df['Monthly_Income'].unique()
print("Valores únicos en la columna 'Monthly_Income':")
print(valores_unicos_Monthly_Income)

Valores únicos en la columna 'Marital_Status':
[nan 'Married' 'Divorced' 'Single']

In [5]:
frecuencia_marital_status = df['Marital_Status'].value_counts()
print("\nFrecuencia de cada valor único en la columna 'Marital_Status':")
print(frecuencia_marital_status)

Frecuencia de cada valor único en la columna 'Marital_Status':
Married     400
Single      301
Divorced    183
Name: Marital_Status, dtype: int64

In [7]:
nulos_Marital_Status_count = df['Marital_Status'].isnull().sum()
print(f"Número de valores nulos en 'Marital_Status': {nulos_Marital_Status_count}")

Número de valores nulos en 'Marital_Status': 593

In [8]:
# Mostrar todas las filas con valores nulos en la columna Marital_Status
nulos_Marital_Status = df[df['Marital_Status'].isnull()]
print("Filas con valores nulos en 'Marital_Status':")
print(nulos_Marital_Status)

# Contar el número de valores nulos en la columna Marital_Status
nulos_Marital_Status_count = df['Marital_Status'].isnull().sum()
print(f"\nNúmero de valores nulos en 'Marital_Status': {nulos_Marital_Status_count}")

Filas con valores nulos en 'Marital_Status':
      Employee_Number  Age  Age_Group  Attrition    Business_Travel  \
0                 162   51        NaN      False                NaN
1                 259   52        NaN      False                NaN
5                1900   48        NaN      False                NaN
6                  81   59        NaN      False                NaN
9                 999   41        NaN      False  Travel_Frequently
10               1035   41        NaN      False         Non_Travel
15                558   40        NaN      False      Travel_Rarely
17               2075   46        NaN      False      Travel_Rarely
19               2077   40        NaN      False      Travel_Rarely
20               1712   45        NaN      False         Non_Travel
24               2079   36        NaN      False      Travel_Rarely
29               1774   34        NaN      False         Non_Travel
31               1993   47        NaN      False                NaN
32                 32   53        NaN      False      Travel_Rarely
51               1527   46        NaN      False                NaN
56                107   38        NaN      False                NaN
57                170   49        NaN      False                NaN
62                691   35        NaN      False                NaN
68               1375   40        NaN      False                NaN
70               2091   35        NaN      False         Non_Travel
71               2092   50        NaN      False                NaN
72               1661   49        NaN      False                NaN
73               1668   38        NaN      False  Travel_Frequently
74               1698   33        NaN      False                NaN
77               2017   37        NaN      False      Travel_Rarely
81               2094   43        NaN      False                NaN
83               2095   47        NaN      False                NaN
89               1277   45        NaN       True                NaN
90               2098   51        NaN      False  Travel_Frequently
91               1666   43        NaN      False      Travel_Rarely
92               1696   34        NaN      False                NaN
94               2099   48        NaN      False                NaN
96               2016   32        NaN      False      Travel_Rarely
100               206   45        NaN      False                NaN
101               228   30        NaN      False      Travel_Rarely
102               239   30        NaN      False                NaN
105               339   34        NaN      False                NaN
107              2102   45        NaN      False  Travel_Frequently
111               452   45        NaN      False      Travel_Rarely
112               456   30        NaN      False      Travel_Rarely
113              2104   31        NaN      False                NaN
117               600   35        NaN      False                NaN
120               638   49        NaN      False                NaN
124               901   53        NaN      False      Travel_Rarely
126               984   35        NaN      False                NaN
132              2107   30        NaN      False      Travel_Rarely
138              2109   34        NaN      False  Travel_Frequently
140              1336   55        NaN      False      Travel_Rarely
141              1352   51        NaN      False                NaN
146              1480   42        NaN      False  Travel_Frequently
149              1520   54        NaN      False  Travel_Frequently
150              1535   34        NaN      False      Travel_Rarely
152              1596   35        NaN      False      Travel_Rarely
153              1667   35        NaN       True                NaN
155              1706   43        NaN      False                NaN
163              2056   39        NaN      False      Travel_Rarely
166                57   30        NaN      False  Travel_Frequently
170               118   46        NaN       True                NaN
171               121   30        NaN      False      Travel_Rarely
176               253   40        NaN      False      Travel_Rarely
179               292   30        NaN      False         Non_Travel
180               306   37        NaN      False                NaN
182               335   40        NaN      False                NaN
185               421   38        NaN      False                NaN
187               531   39        NaN      False                NaN
188               549   60        NaN      False                NaN
189               567   30        NaN      False                NaN
193               772   32        NaN      False                NaN
194               836   42        NaN      False                NaN
199               889   32        NaN      False                NaN
200               924   36        NaN      False                NaN
201              2122   31        NaN      False         Non_Travel
205              1002   45        NaN      False         Non_Travel
206              1073   36        NaN      False      Travel_Rarely
207              1138   49        NaN      False                NaN
208              2124   29        NaN       True                NaN
211              2125   33        NaN      False      Travel_Rarely
214              1324   31        NaN      False         Non_Travel
215              1334   42        NaN      False         Non_Travel
218              1423   58        NaN      False      Travel_Rarely
219              1459   31        NaN       True  Travel_Frequently
220              2127   40        NaN      False         Non_Travel
222              1485   34        NaN      False                NaN
225              1547   42        NaN      False  Travel_Frequently
229              1606   50        NaN      False                NaN
230              2129   39        NaN      False      Travel_Rarely
231              1658   34        NaN      False      Travel_Rarely
232              1665   54        NaN      False      Travel_Rarely
233              2130   41        NaN      False      Travel_Rarely
235              2131   40        NaN      False      Travel_Rarely
236              2132   33        NaN      False                NaN
237              1790   36        NaN      False                NaN
239              1823   34        NaN      False      Travel_Rarely
244              1888   45        NaN      False      Travel_Rarely
245              1950   34        NaN      False      Travel_Rarely
247              1962   35        NaN      False                NaN
255              2138   32        NaN      False                NaN
256              2139   38        NaN      False  Travel_Frequently
257              2140   36        NaN      False      Travel_Rarely
258                35   42        NaN      False                NaN
261               120   51        NaN      False                NaN
262               147   34        NaN       True  Travel_Frequently
263               154   36        NaN      False                NaN
268               177   26        NaN      False      Travel_Rarely
271               205   53        NaN      False      Travel_Rarely
273              2142   36        NaN      False  Travel_Frequently
274               252   33        NaN      False      Travel_Rarely
277               267   37        NaN      False                NaN
283              2144   33        NaN       True      Travel_Rarely
284               329   52        NaN      False                NaN
285              2145   40        NaN      False                NaN
286               361   38        NaN      False         Non_Travel
289               500   51        NaN      False      Travel_Rarely
290               586   35        NaN      False      Travel_Rarely
292              2146   28        NaN       True                NaN
294              2147   40        NaN      False                NaN
295              2148   28        NaN      False                NaN
297               941   31        NaN      False      Travel_Rarely
299              2150   46        NaN      False                NaN
300              1013   54        NaN      False      Travel_Rarely
301              1015   30        NaN      False      Travel_Rarely
306              1050   53        NaN      False  Travel_Frequently
311              1100   35        NaN       True                NaN
314              1119   38        NaN      False                NaN
315              2153   28        NaN      False                NaN
317              2154   39        NaN       True  Travel_Frequently
318              1128   40        NaN      False      Travel_Rarely
320              2156   40        NaN      False                NaN
321              1177   26        NaN      False      Travel_Rarely
324              1218   35        NaN      False                NaN
325              1220   33        NaN      False                NaN
331              2159   27        NaN      False      Travel_Rarely
332              1255   43        NaN      False                NaN
342              1344   34        NaN      False                NaN
343              1355   38        NaN      False                NaN
345              1369   35        NaN      False                NaN
346              2164   55        NaN       True                NaN
347              1377   34        NaN      False                NaN
352              1422   54        NaN      False                NaN
354              2165   40        NaN      False         Non_Travel
357              1460   45        NaN      False      Travel_Rarely
359              1497   29        NaN      False      Travel_Rarely
361              1544   29        NaN      False                NaN
365              1608   44        NaN      False                NaN
366              1611   45        NaN      False                NaN
367              1612   45        NaN      False         Non_Travel
368              1615   34        NaN      False  Travel_Frequently
369              2169   39        NaN      False                NaN
375              1691   48        NaN       True  Travel_Frequently
376              1693   26        NaN      False                NaN
377              1703   44        NaN      False      Travel_Rarely
381              1745   30        NaN      False  Travel_Frequently
382              1754   30        NaN      False                NaN
383              1756   33        NaN      False         Non_Travel
390              1965   27        NaN      False      Travel_Rarely
391              1967   31        NaN       True  Travel_Frequently
394              2008   35        NaN      False                NaN
401              2062   39        NaN      False      Travel_Rarely
413               764   27        NaN      False                NaN
414              2179   52        NaN      False      Travel_Rarely
416               903   47        NaN      False      Travel_Rarely
421              1085   41        NaN      False                NaN
423              1109   42        NaN      False                NaN
425              1152   38        NaN      False                NaN
426              2182   46        NaN      False                NaN
430              1539   50        NaN      False                NaN
431              2183   55        NaN      False      Travel_Rarely
433              1617   49        NaN      False                NaN
435              2184   46        NaN      False                NaN
440                60   34        NaN      False         Non_Travel
444               346   29        NaN      False      Travel_Rarely
445               384   26        NaN      False                NaN
448               604   31        NaN      False      Travel_Rarely
452              2189   24        NaN      False      Travel_Rarely
454               649   34        NaN      False                NaN
455               714   27        NaN      False  Travel_Frequently
458               804   34        NaN      False                NaN
460               856   35        NaN      False                NaN
468              2195   26        NaN      False                NaN
469              1438   47        NaN      False      Travel_Rarely
473              2197   33        NaN      False         Non_Travel
475              2199   41        NaN       True                NaN
478              2201   32        NaN      False      Travel_Rarely
480               112   56        NaN      False                NaN
481               129   28        NaN      False                NaN
483               161   56        NaN       True                NaN
485               190   32        NaN       True                NaN
487               226   50        NaN      False      Travel_Rarely
488               231   32        NaN      False                NaN
489               240   45        NaN      False      Travel_Rarely
492               308   31        NaN      False         Non_Travel
494               355   31        NaN       True                NaN
495               378   37        NaN      False                NaN
498              2205   27        NaN      False                NaN
499               449   27        NaN      False         Non_Travel
501               486   37        NaN      False      Travel_Rarely
502               492   40        NaN       True                NaN
504               510   26        NaN       True  Travel_Frequently
509               547   42        NaN      False  Travel_Frequently
510               548   30        NaN      False      Travel_Rarely
514              2211   25        NaN      False                NaN
516               785   47        NaN       True                NaN
519               878   36        NaN      False      Travel_Rarely
520               895   31        NaN      False                NaN
522              2212   39        NaN      False      Travel_Rarely
523               936   42        NaN      False                NaN
524              2213   30        NaN      False      Travel_Rarely
526              1048   59        NaN      False      Travel_Rarely
531              2215   35        NaN      False      Travel_Rarely
535              2216   33        NaN      False                NaN
536              1245   54        NaN      False  Travel_Frequently
539              1309   32        NaN       True      Travel_Rarely
545              1397   39        NaN      False         Non_Travel
550              2220   34        NaN      False      Travel_Rarely
552              2221   33        NaN      False      Travel_Rarely
556              1548   40        NaN      False      Travel_Rarely
557              2222   29        NaN      False                NaN
560              1609   30        NaN      False                NaN
561              1638   38        NaN      False                NaN
563              2223   39        NaN      False      Travel_Rarely
566              1704   35        NaN      False                NaN
570              2224   40        NaN      False                NaN
572              1909   41        NaN      False                NaN
575              1949   36        NaN      False         Non_Travel
578              2227   31        NaN      False         Non_Travel
580                46   43        NaN      False      Travel_Rarely
582                68   44        NaN      False                NaN
587               126   54        NaN      False      Travel_Rarely
588              2228   50        NaN      False                NaN
591              2229   37        NaN      False      Travel_Rarely
593               216   34        NaN      False  Travel_Frequently
596              2231   41        NaN       True      Travel_Rarely
599               299   30        NaN       True                NaN
602               369   25        NaN      False                NaN
605              2232   28        NaN      False                NaN
609               450   54        NaN      False  Travel_Frequently
611               469   29        NaN      False         Non_Travel
612               491   50        NaN      False      Travel_Rarely
615               579   34        NaN      False                NaN
621              2237   24        NaN       True  Travel_Frequently
625               758   23        NaN      False      Travel_Rarely
626               760   39        NaN      False      Travel_Rarely
627               791   52        NaN      False         Non_Travel
631               815   50        NaN      False      Travel_Rarely
633              2240   38        NaN      False  Travel_Frequently
636              2242   25        NaN      False                NaN
639              2244   29        NaN      False      Travel_Rarely
640               983   38        NaN      False         Non_Travel
642              1011   31        NaN      False  Travel_Frequently
643              1019   22        NaN      False                NaN
644              1032   59        NaN      False      Travel_Rarely
646              1049   45        NaN      False      Travel_Rarely
647              2245   37        NaN      False      Travel_Rarely
648              1068   26        NaN      False                NaN
660              1349   41        NaN      False  Travel_Frequently
664              1420   49        NaN       True  Travel_Frequently
665              1431   34        NaN      False  Travel_Frequently
666              1446   32        NaN      False                NaN
667              1477   33        NaN      False                NaN
669              1499   30        NaN      False                NaN
671              1545   33        NaN      False                NaN
673              1563   38        NaN      False  Travel_Frequently
675              1631   37        NaN      False                NaN
676              1646   24        NaN      False                NaN
677              1659   36        NaN      False                NaN
678              2249   38        NaN      False  Travel_Frequently
680              1700   37        NaN      False  Travel_Frequently
682              2251   29        NaN      False      Travel_Rarely
686              1792   44        NaN       True                NaN
691              1822   40        NaN      False                NaN
692              2255   26        NaN      False      Travel_Rarely
695              1885   37        NaN      False      Travel_Rarely
696              1931   27        NaN      False                NaN
697              1945   35        NaN      False      Travel_Rarely
701              1998   42        NaN      False                NaN
702              1999   41        NaN      False                NaN
703              2018   25        NaN      False      Travel_Rarely
705              2044   50        NaN       True                NaN
707              2046   45        NaN      False                NaN
710              2053   29        NaN      False      Travel_Rarely
711              2068   34        NaN      False                NaN
718                26   24        NaN      False                NaN
720                33   32        NaN       True  Travel_Frequently
727              2259   35        NaN      False      Travel_Rarely
729               102   37        NaN      False      Travel_Rarely
732               116   51        NaN      False      Travel_Rarely
736              2260   59        NaN      False         Non_Travel
740               175   31        NaN       True      Travel_Rarely
742               179   51        NaN       True  Travel_Frequently
743              2262   25        NaN      False                NaN
744               193   38        NaN      False      Travel_Rarely
747               218   27        NaN      False         Non_Travel

In [9]:
moda_scores = df['Marital_Status'].mode()[0]

# Imputar valores nulos con la moda
df['Marital_Status'].fillna(moda_scores, inplace=True)

print(df)

      Employee_Number  Age  Age_Group  Attrition    Business_Travel  \
0                 162   51        NaN      False                NaN
1                 259   52        NaN      False                NaN
2                 319   42        NaN      False      Travel_Rarely
3                2069   47        NaN      False      Travel_Rarely
4                2070   46        NaN      False                NaN
5                1900   48        NaN      False                NaN
6                  81   59        NaN      False                NaN
7                 387   42        NaN      False      Travel_Rarely
8                2071   41        NaN      False                NaN
9                 999   41        NaN      False  Travel_Frequently
10               1035   41        NaN      False         Non_Travel
11               2072   56        NaN      False      Travel_Rarely
12               2073   38        NaN      False                NaN
13                 58   41        NaN       True      Travel_Rarely
14               2074   55        NaN      False                NaN
15                558   40        NaN      False      Travel_Rarely
16                825   58        NaN       True      Travel_Rarely
17               2075   46        NaN      False      Travel_Rarely
18               2076   35        NaN      False                NaN
19               2077   40        NaN      False      Travel_Rarely
20               1712   45        NaN      False         Non_Travel
21                 73   33        NaN      False                NaN
22               2078   36        NaN      False                NaN
23                820   47        NaN      False                NaN
24               2079   36        NaN      False      Travel_Rarely
25               2080   35        NaN      False                NaN
26               2081   52        NaN       True                NaN
27               1294   36        NaN      False                NaN
28               2082   33        NaN      False      Travel_Rarely
29               1774   34        NaN      False         Non_Travel
30               1815   41        NaN      False                NaN
31               1993   47        NaN      False                NaN
32                 32   53        NaN      False      Travel_Rarely
33                100   35        NaN      False                NaN
34               2083   34        NaN      False      Travel_Rarely
35                244   46        NaN      False      Travel_Rarely
36                327   43        NaN      False                NaN
37                373   36        NaN      False                NaN
38               2084   60        NaN      False  Travel_Frequently
39                729   40        NaN      False  Travel_Frequently
40                830   32        NaN      False      Travel_Rarely
41               2085   41        NaN      False      Travel_Rarely
42                981   53        NaN      False                NaN
43               1042   36        NaN       True      Travel_Rarely
44               1080   46        NaN      False                NaN
45               1995   38        NaN      False      Travel_Rarely
46                145   51        NaN      False                NaN
47                158   43        NaN      False                NaN
48                391   37        NaN      False                NaN
49                436   32        NaN      False      Travel_Rarely
50               2086   38        NaN      False                NaN
51               1527   46        NaN      False                NaN
52               2087   35        NaN       True      Travel_Rarely
53               1866   43        NaN      False                NaN
54               2026   56        NaN      False         Non_Travel
55               2088   36        NaN      False         Non_Travel
56                107   38        NaN      False                NaN
57                170   49        NaN      False                NaN
58               2089   39        NaN      False      Travel_Rarely
59                215   40        NaN      False                NaN
60                304   36        NaN      False                NaN
61                529   37        NaN      False                NaN
62                691   35        NaN      False                NaN
63                692   33        NaN      False  Travel_Frequently
64               1005   50        NaN      False      Travel_Rarely
65               1024   48        NaN      False      Travel_Rarely
66               1039   44        NaN      False      Travel_Rarely
67               1225   44        NaN      False      Travel_Rarely
68               1375   40        NaN      False                NaN
69               2090   34        NaN      False      Travel_Rarely
70               2091   35        NaN      False         Non_Travel
71               2092   50        NaN      False                NaN
72               1661   49        NaN      False                NaN
73               1668   38        NaN      False  Travel_Frequently
74               1698   33        NaN      False                NaN
75               2093   47        NaN      False      Travel_Rarely
76               1937   38        NaN      False                NaN
77               2017   37        NaN      False      Travel_Rarely
78                117   30        NaN      False                NaN
79                131   58        NaN      False      Travel_Rarely
80                153   34        NaN      False      Travel_Rarely
81               2094   43        NaN      False                NaN
82                899   35        NaN      False                NaN
83               2095   47        NaN      False                NaN
84               1014   35        NaN      False                NaN
85               2096   40        NaN      False      Travel_Rarely
86               1117   45        NaN      False                NaN
87               1238   33        NaN      False                NaN
88               2097   36        NaN      False  Travel_Frequently
89               1277   45        NaN       True                NaN
90               2098   51        NaN      False  Travel_Frequently
91               1666   43        NaN      False      Travel_Rarely
92               1696   34        NaN      False                NaN
93               1805   38        NaN      False                NaN
94               2099   48        NaN      False                NaN
95               1932   34        NaN      False                NaN
96               2016   32        NaN      False      Travel_Rarely
97                 20   29        NaN      False      Travel_Rarely
98               2100   46        NaN      False                NaN
99                184   30        NaN      False                NaN
100               206   45        NaN      False                NaN
101               228   30        NaN      False      Travel_Rarely
102               239   30        NaN      False                NaN
103               256   34        NaN      False  Travel_Frequently
104              2101   51        NaN      False      Travel_Rarely
105               339   34        NaN      False                NaN
106               406   35        NaN      False      Travel_Rarely
107              2102   45        NaN      False  Travel_Frequently
108               429   39        NaN      False                NaN
109              2103   31        NaN      False                NaN
110               444   39        NaN      False                NaN
111               452   45        NaN      False      Travel_Rarely
112               456   30        NaN      False      Travel_Rarely
113              2104   31        NaN      False                NaN
114               481   36        NaN      False                NaN
115               513   36        NaN      False      Travel_Rarely
116               597   55        NaN      False      Travel_Rarely
117               600   35        NaN      False                NaN
118              2105   42        NaN      False      Travel_Rarely
119               630   52        NaN      False      Travel_Rarely
120               638   49        NaN      False                NaN
121               683   34        NaN      False      Travel_Rarely
122               780   33        NaN       True      Travel_Rarely
123               817   33        NaN      False                NaN
124               901   53        NaN      False      Travel_Rarely
125               944   49        NaN      False      Travel_Rarely
126               984   35        NaN      False                NaN
127              1088   38        NaN      False      Travel_Rarely
128              1124   46        NaN      False                NaN
129              2106   36        NaN      False         Non_Travel
130              1167   42        NaN       True  Travel_Frequently
131              1184   34        NaN      False  Travel_Frequently
132              2107   30        NaN      False      Travel_Rarely
133              2108   54        NaN      False      Travel_Rarely
134              1252   31        NaN      False      Travel_Rarely
135              1267   44        NaN      False                NaN
136              1278   55        NaN      False         Non_Travel
137              1288   44        NaN      False      Travel_Rarely
138              2109   34        NaN      False  Travel_Frequently
139              1307   39        NaN      False                NaN
140              1336   55        NaN      False      Travel_Rarely
141              1352   51        NaN      False                NaN
142              1360   58        NaN       True                NaN
143              2110   48        NaN      False                NaN
144              1419   29        NaN      False      Travel_Rarely
145              1478   34        NaN      False                NaN
146              1480   42        NaN      False  Travel_Frequently
147              2111   57        NaN      False      Travel_Rarely
148              1489   34        NaN       True      Travel_Rarely
149              1520   54        NaN      False  Travel_Frequently
150              1535   34        NaN      False      Travel_Rarely
151              1586   29        NaN      False                NaN
152              1596   35        NaN      False      Travel_Rarely
153              1667   35        NaN       True                NaN
154              1701   34        NaN      False      Travel_Rarely
155              1706   43        NaN      False                NaN
156              2112   58        NaN      False         Non_Travel
157              2113   36        NaN      False      Travel_Rarely
158              1971   43        NaN      False      Travel_Rarely
159              2114   55        NaN      False                NaN
160              1976   42        NaN      False                NaN
161              1985   40        NaN      False                NaN
162              2032   56        NaN       True                NaN
163              2056   39        NaN      False      Travel_Rarely
164              2115   53        NaN      False      Travel_Rarely
165              2116   27        NaN      False  Travel_Frequently
166                57   30        NaN      False  Travel_Frequently
167              2117   35        NaN      False                NaN
168                78   32        NaN      False      Travel_Rarely
169               104   30        NaN      False      Travel_Rarely
170               118   46        NaN       True                NaN
171               121   30        NaN      False      Travel_Rarely
172               125   32        NaN      False                NaN
173              2118   35        NaN      False      Travel_Rarely
174               207   32        NaN      False                NaN
175               227   41        NaN      False      Travel_Rarely
176               253   40        NaN      False      Travel_Rarely
177               264   45        NaN      False                NaN
178               291   32        NaN       True      Travel_Rarely
179               292   30        NaN      False         Non_Travel
180               306   37        NaN      False                NaN
181              2119   37        NaN      False                NaN
182               335   40        NaN      False                NaN
183              2120   36        NaN      False         Non_Travel
184               420   32        NaN      False      Travel_Rarely
185               421   38        NaN      False                NaN
186               441   30        NaN      False      Travel_Rarely
187               531   39        NaN      False                NaN
188               549   60        NaN      False                NaN
189               567   30        NaN      False                NaN
190               581   31        NaN      False      Travel_Rarely
191               702   33        NaN       True                NaN
192               716   50        NaN      False                NaN
193               772   32        NaN      False                NaN
194               836   42        NaN      False                NaN
195               840   49        NaN       True                NaN
196               844   27        NaN      False                NaN
197              2121   33        NaN      False      Travel_Rarely
198               867   52        NaN      False                NaN
199               889   32        NaN      False                NaN
200               924   36        NaN      False                NaN
201              2122   31        NaN      False         Non_Travel
202              2123   36        NaN      False      Travel_Rarely
203               976   52        NaN      False                NaN
204               992   33        NaN      False         Non_Travel
205              1002   45        NaN      False         Non_Travel
206              1073   36        NaN      False      Travel_Rarely
207              1138   49        NaN      False                NaN
208              2124   29        NaN       True                NaN
209              1192   29        NaN      False                NaN
210              1196   37        NaN      False                NaN
211              2125   33        NaN      False      Travel_Rarely
212              2126   34        NaN      False  Travel_Frequently
213              1315   28        NaN      False         Non_Travel
214              1324   31        NaN      False         Non_Travel
215              1334   42        NaN      False         Non_Travel
216              1346   40        NaN      False      Travel_Rarely
217              1356   34        NaN      False                NaN
218              1423   58        NaN      False      Travel_Rarely
219              1459   31        NaN       True  Travel_Frequently
220              2127   40        NaN      False         Non_Travel
221              1472   53        NaN      False                NaN
222              1485   34        NaN      False                NaN
223              2128   35        NaN      False      Travel_Rarely
224              1543   37        NaN      False                NaN
225              1547   42        NaN      False  Travel_Frequently
226              1553   45        NaN      False                NaN
227              1562   30        NaN       True      Travel_Rarely
228              1582   38        NaN      False      Travel_Rarely
229              1606   50        NaN      False                NaN
230              2129   39        NaN      False      Travel_Rarely
231              1658   34        NaN      False      Travel_Rarely
232              1665   54        NaN      False      Travel_Rarely
233              2130   41        NaN      False      Travel_Rarely
234              1737   39        NaN      False                NaN
235              2131   40        NaN      False      Travel_Rarely
236              2132   33        NaN      False                NaN
237              1790   36        NaN      False                NaN
238              2133   33        NaN      False                NaN
239              1823   34        NaN      False      Travel_Rarely
240              2134   29        NaN      False  Travel_Frequently
241              1857   46        NaN      False      Travel_Rarely
242              1864   27        NaN      False      Travel_Rarely
243              1881   31        NaN      False                NaN
244              1888   45        NaN      False      Travel_Rarely
245              1950   34        NaN      False      Travel_Rarely
246              2135   31        NaN      False                NaN
247              1962   35        NaN      False                NaN
248              1975   39        NaN      False      Travel_Rarely
249              1986   40        NaN      False      Travel_Rarely
250              2136   30        NaN      False      Travel_Rarely
251              2000   47        NaN      False                NaN
252              2137   52        NaN      False         Non_Travel
253                 2   49        NaN      False  Travel_Frequently
254                 5   33        NaN      False  Travel_Frequently
255              2138   32        NaN      False                NaN
256              2139   38        NaN      False  Travel_Frequently
257              2140   36        NaN      False      Travel_Rarely
258                35   42        NaN      False                NaN
259                76   31        NaN      False                NaN
260                98   31        NaN      False      Travel_Rarely
261               120   51        NaN      False                NaN
262               147   34        NaN       True  Travel_Frequently
263               154   36        NaN      False                NaN
264               159   30        NaN      False  Travel_Frequently
265               160   33        NaN      False         Non_Travel
266               163   31        NaN       True                NaN
267               176   41        NaN      False      Travel_Rarely
268               177   26        NaN      False      Travel_Rarely
269               195   32        NaN      False                NaN
270               202   40        NaN      False  Travel_Frequently
271               205   53        NaN      False      Travel_Rarely
272              2141   29        NaN      False         Non_Travel
273              2142   36        NaN      False  Travel_Frequently
274               252   33        NaN      False      Travel_Rarely
275               258   51        NaN      False      Travel_Rarely
276               260   27        NaN      False      Travel_Rarely
277               267   37        NaN      False                NaN
278              2143   38        NaN      False                NaN
279               275   49        NaN      False         Non_Travel
280               293   27        NaN      False                NaN
281               302   45        NaN      False                NaN
282               314   35        NaN      False                NaN
283              2144   33        NaN       True      Travel_Rarely
284               329   52        NaN      False                NaN
285              2145   40        NaN      False                NaN
286               361   38        NaN      False         Non_Travel
287               363   46        NaN      False                NaN
288               389   55        NaN      False      Travel_Rarely
289               500   51        NaN      False      Travel_Rarely
290               586   35        NaN      False      Travel_Rarely
291               710   29        NaN      False                NaN
292              2146   28        NaN       True                NaN

In [10]:
frecuencia_marital_status = df['Marital_Status'].value_counts()
print("\nFrecuencia de cada valor único en la columna 'Marital_Status':")
print(frecuencia_marital_status)

Frecuencia de cada valor único en la columna 'Marital_Status':
Married     993
Single      301
Divorced    183
Name: Marital_Status, dtype: int64

MONTHLY_INCOME

In [12]:
valores_unicos_monthly = df['Monthly_Income'].unique()
print("Valores únicos en la columna 'Monthly_Income':")
print(valores_unicos_monthly)

Valores únicos en la columna 'Monthly_Income':
[19537. 19999. 19232. 17169.    nan 17174. 16595. 19973. 13402. 13206.
 19545. 18041. 19246. 10748. 16752.  6201. 19845.  4001. 10447. 16064.
  3210. 10266. 10475.  6162.  4721.  4615. 16959. 10306.  5406.  5902.
 10855.  5914.  6646. 13973. 13320.  6687.  4735. 13872.  5067.  3692.
 19847.  5747. 10422.  6347.  2348.  3072. 12490.  8020. 17068.  8943.
 19272.  5577.  2691.  7403.  8823.  3579. 17779. 18213. 13577. 19190.
 17123. 19187. 10008.  7988.  7083.  4723.  3407.  2929. 12031. 15427.
  5126.  9619.  5010. 19033. 10400.  2793.  5674. 19197.  8412.  3348.
  5309.  7654. 12808.  6586.  2519. 17099. 13120.  3131.  4444.  6674.
  9852. 17861.  7446. 13757. 16598.  4285. 10124.  9714.  9924. 11245.
  3069.  9241.  6472.  3055.  8321.  3143.  8578.  4197.  9888. 13341.
  5677.  2909.  9526.  6825.  4424.  5441.  6074.  6146.  6172.  4668.
  5605.  4319.  3564.  6261.  6804. 19436.  2216.  5304.  4244.  2329.
 10845.  5472.  6385.  7525.  3660.  8740. 13499.  3491.  5220. 10252.
 19740.  6209.  7094.  4534.  8500.  4639.  5363.  4081.  3578. 17328.
 10793. 10851. 10466.  2362.  6439.  5769.  4385.  4066.  5206.  2655.
  2570.  4502.  4968.  5147.  2718.  9667.  5154.  5098. 13570.  6712.
  9991. 10248. 10938.  2593. 11878.  8095. 16856.  4537. 17924.  4014.
 12742.  3376. 10482.  4249.  6549. 14411. 19586.  8237.  3211. 16704.
  4774.  4568.  5993.  6499.  3452.  6397.  2725.  3622.  6180.  6274.
  4381.  2559.  5488.  2514.  3196.  3420.  4087.  5368. 12936.  4221.
  4963.  4200.  5006.  7639.  6502. 13525.  6349.  6380.  3102.  4556.
  4230.  4859.  6322. 10761.  2973.  5204. 17399. 16885.  4323.  5155.
  2936. 18789.  4883.  2029.  2996.  9278.  4162.  8853.  4876.  2141.
  7756.  3936.  6842.  3989.  4930.  3702.  2705.  4448.  2379.  5487.
  2810.  8938.  9936.  5454. 18740.  5473. 13503. 13549. 18172.  2774.
  9439.  5265.  3815.  2389.  4000. 17584.  5661.  4869.  4649. 10496.
  2768.  3408.  3755.  2187.  4258.  5326.  5485.  2782. 17639.  6062.
  6288.  3424.  4194.  2532.  5666. 13726.  4107.  3597.  4115.  6272.
  2517.  3904.  9204.  4373.  2064.  2430.  4877.  3760.  2013.  2974.
  2766.  3377.  4213.  6513.  4284.  2226.  5561.  2897.  5321.  5410.
  4850.  2001.  4404.  3944.  2960. 18947.  6465.  2683.  2014.  3441.
 13664.  5021. 18844.  4739. 10650.  4317.  2024.  3058.  3929.  4425.
  2328.  2657.  5940.  2622.  3212.  2911.  6931.  2176.  3230. 18665.
  2789. 11935.  2546.  3894.  4262. 10527.  2400.  3681.  3447. 19513.
  2659.  8847.  2045.  4851.  8120.  4577.  5405.  3708. 13770.  2297.
  2450.  4342.  2572.  6500.  3149.  5324.  4382.  2553.  5933.  4403.
 10934.  2022.  4256.  3580.  2899.  5562.  2377.  2404.  2799.  2811.
  4377.  4240.  4227.  3917.  4969.  9957.  2207. 19081.  2743.  4538.
  3867.  2080.  2096.  4627.  2302.  5071. 10596.  5467.  2394.  3629.
  9362.  3229. 16422.  5647.  4400.  2066.  5486.  3162.  6651.  4898.
  3180. 11244.  4069.  6392.  4855.  3312.  3117. 15202.  2580.  2166.
  4374.  5505.  2587. 15972.  2305.  3433.  3477.  3907.  3445.  2760.
  6294. 13116.  3591.  2105.  3902.  2662.  2062.  5507.  8103.  3978.
  5399. 10448.  4440.  2660.  3375.  2269.  4787.  2809. 10854.  2571.
  6142.  2496.  3419.  2501.  2566.  3920. 13964.  6540.  2244. 16184.
  4233. 14814. 17159.  2318.  3617.  2684. 19237.  4422.  2552.  2678.
  5171. 11916.  9380.  5878.  2468.  4127.  2148.  3886.  6667.  2090.
  2086.  1951.  3022.  9724.  3388.  3038.  2322.  2926.  4505.  2835.
  6553.  6673. 13591.  2177. 19517. 19202. 10048.  2723.  6644.  3161.
  1420.  1200.  5238.  9985. 15992.  2370.  6781.  6653.  2851.  5258.
  2476.  2285.  3448.  4558.  1702.  2564.  5070.  3780.  9824.  1878.
  2340.  2127.  2033.  9602. 16627.  2083.  1009.  7861.  2642.  5121.
  2694.  5094.  2274.  2314.  2380.  2008. 10552.  2259.  2413.  2121.
  2479. 13194.  4163.  2600. 18303.  4777.  1052.  2461.  2596.  4728.
  7351.  4766.  2258.  2827.  2853.  2290.  2107.  2210. 13191. 18265.
  1118.  2372.  2838. 18061.  1611.  4768.  1274.  2561.  1563.  6388.
  8376.  4841.  2074.  2972.  6815.  2690. 17567.  1569.  4187.  3306.
  1393. 10883.  2862.  6735.  9756.  5294.  2437.  4071.  2956.  4648.
  2804.  2439.  2856.  2933.  1091.  5151.  2863.  2858.  1129. 19431.
  2308.  2144.  5373. 19045. 16015.  9613. 11510.  4306. 17046.  2042.
  2821.  2070.  2791.  8224.  2610.  5731.  2539.  2376.  3539.  5468.
  5813.  5675.  7314.  6410.  4941.  3983.  2904.  2696.  2174.  6755.
 10965.  2543. 19406.  6538.  2218.  2654.  5828.  2455.  5055.  4682.
  5257.  2119.  5974.  3034. 13212.  8392.  4051.  4805.  2741.  5337.
  9434.  5396. 11159.  4960.  8793. 19189. 11713. 11103.  6632.  7587.
  4335.  5980.  5228.  2700.  2366.  4294.  6725. 10325.  4447.]

In [13]:
frecuencia_monthly = df['Monthly_Income'].value_counts()
print("\nFrecuencia de cada valor único en la columna 'Monthly_Income':")
print(frecuencia_monthly)

Frecuencia de cada valor único en la columna 'Monthly_Income':
6347.0     3
3904.0     2
4197.0     2
3420.0     2
2782.0     2
5605.0     2
5769.0     2
2380.0     2
2033.0     2
6162.0     2
2909.0     2
7756.0     2
2258.0     2
2404.0     2
5154.0     2
3452.0     2
2587.0     2
4244.0     2
10845.0    2
17861.0    2
3760.0     2
2657.0     2
2377.0     2
5304.0     2
2216.0     2
5405.0     2
13964.0    1
2244.0     1
2566.0     1
6540.0     1
16184.0    1
4233.0     1
2501.0     1
3920.0     1
19537.0    1
3419.0     1
4440.0     1
2662.0     1
2062.0     1
5507.0     1
8103.0     1
3978.0     1
5399.0     1
10448.0    1
2660.0     1
2496.0     1
3375.0     1
2269.0     1
4787.0     1
2809.0     1
10854.0    1
14814.0    1
6142.0     1
2571.0     1
4422.0     1
17159.0    1
2318.0     1
3388.0     1
3038.0     1
2322.0     1
2926.0     1
4505.0     1
2835.0     1
6553.0     1
6673.0     1
13591.0    1
2177.0     1
19517.0    1
19202.0    1
10048.0    1
2723.0     1
6644.0     1
3161.0     1
1420.0     1
9724.0     1
3022.0     1
1951.0     1
11916.0    1
3617.0     1
2684.0     1
19237.0    1
2105.0     1
2552.0     1
2678.0     1
5171.0     1
9380.0     1
2086.0     1
5878.0     1
2468.0     1
4127.0     1
2148.0     1
3886.0     1
6667.0     1
2090.0     1
3902.0     1
3445.0     1
3591.0     1
2553.0     1
4403.0     1
10934.0    1
2022.0     1
4256.0     1
3580.0     1
2899.0     1
5562.0     1
2799.0     1
2811.0     1
4377.0     1
4240.0     1
4227.0     1
3917.0     1
4969.0     1
9957.0     1
2207.0     1
19081.0    1
5933.0     1
4382.0     1
4538.0     1
5324.0     1
3681.0     1
3447.0     1
19513.0    1
2659.0     1
8847.0     1
2045.0     1
4851.0     1
8120.0     1
4577.0     1
3708.0     1
13770.0    1
2297.0     1
2450.0     1
4342.0     1
2572.0     1
6500.0     1
3149.0     1
2743.0     1
3867.0     1
13116.0    1
11244.0    1
6392.0     1
4855.0     1
3312.0     1
3117.0     1
15202.0    1
2580.0     1
2166.0     1
4374.0     1
5505.0     1
15972.0    1
2305.0     1
3433.0     1
3477.0     1
3907.0     1
5238.0     1
2760.0     1
6294.0     1
4069.0     1
3180.0     1
2080.0     1
4898.0     1
2096.0     1
4627.0     1
2302.0     1
5071.0     1
10596.0    1
5467.0     1
2394.0     1
3629.0     1
9362.0     1
3229.0     1
16422.0    1
5647.0     1
4400.0     1
2066.0     1
5486.0     1
3162.0     1
6651.0     1
1200.0     1
2476.0     1
9985.0     1
2174.0     1
2821.0     1
2070.0     1
2791.0     1
8224.0     1
2610.0     1
5731.0     1
2539.0     1
2376.0     1
3539.0     1
5468.0     1
5813.0     1
5675.0     1
7314.0     1
6410.0     1
4941.0     1
3983.0     1
2904.0     1
2042.0     1
17046.0    1
4306.0     1
2858.0     1
2804.0     1
2439.0     1
2856.0     1
2933.0     1
1091.0     1
5151.0     1
2863.0     1
1129.0     1
11510.0    1
19431.0    1
2308.0     1
2144.0     1
5373.0     1
19045.0    1
16015.0    1
9613.0     1
2696.0     1
6755.0     1
2956.0     1
10965.0    1
5396.0     1
11159.0    1
4960.0     1
8793.0     1
19189.0    1
11713.0    1
11103.0    1
6632.0     1
7587.0     1
4335.0     1
5980.0     1
5228.0     1
2700.0     1
2366.0     1
4294.0     1
6725.0     1
10325.0    1
9434.0     1
5337.0     1
2741.0     1
5055.0     1
2543.0     1
19406.0    1
6538.0     1
2218.0     1
2654.0     1
5828.0     1
2455.0     1
4682.0     1
4805.0     1
5257.0     1
2119.0     1
5974.0     1
3034.0     1
13212.0    1
8392.0     1
4051.0     1
4648.0     1
4071.0     1
15992.0    1
4777.0     1
1009.0     1
7861.0     1
2642.0     1
5121.0     1
2694.0     1
5094.0     1
2274.0     1
2314.0     1
2008.0     1
10552.0    1
2259.0     1
2413.0     1
2121.0     1
2479.0     1
13194.0    1
4163.0     1
2600.0     1
2083.0     1
16627.0    1
9602.0     1
3448.0     1
2370.0     1
6781.0     1
6653.0     1
2851.0     1
5258.0     1
10527.0    1
2285.0     1
4558.0     1
2127.0     1
1702.0     1
2564.0     1
5070.0     1
3780.0     1
9824.0     1
1878.0     1
2340.0     1
18303.0    1
1052.0     1
2437.0     1
2461.0     1
6388.0     1
8376.0     1
4841.0     1
2074.0     1
2972.0     1
6815.0     1
2690.0     1
17567.0    1
1569.0     1
4187.0     1
3306.0     1
1393.0     1
10883.0    1
2862.0     1
6735.0     1
9756.0     1
5294.0     1
1563.0     1
2561.0     1
1274.0     1
2107.0     1
2596.0     1
4728.0     1
7351.0     1
4766.0     1
2827.0     1
2853.0     1
2290.0     1
2210.0     1
4768.0     1
13191.0    1
18265.0    1
1118.0     1
2372.0     1
2838.0     1
18061.0    1
1611.0     1
2400.0     1
2911.0     1
4262.0     1
6385.0     1
9888.0     1
13341.0    1
5677.0     1
9526.0     1
6825.0     1
4424.0     1
5441.0     1
6074.0     1
6146.0     1
6172.0     1
4668.0     1
4319.0     1
3564.0     1
6261.0     1
6804.0     1
19436.0    1
2329.0     1
8578.0     1
3143.0     1
8321.0     1
16598.0    1
13120.0    1
3131.0     1
4444.0     1
6674.0     1
9852.0     1
7446.0     1
13757.0    1
4285.0     1
3055.0     1
10124.0    1
9714.0     1
9924.0     1
11245.0    1
3069.0     1
9241.0     1
6472.0     1
5472.0     1
7525.0     1
3894.0     1
3660.0     1
4385.0     1
4066.0     1
5206.0     1
2655.0     1
2570.0     1
4502.0     1
4968.0     1
5147.0     1
2718.0     1
9667.0     1
5098.0     1
13570.0    1
6712.0     1
9991.0     1
10248.0    1
10938.0    1
2593.0     1
6439.0     1
2362.0     1
10466.0    1
7094.0     1
8740.0     1
13499.0    1
3491.0     1
5220.0     1
10252.0    1
19740.0    1
6209.0     1
4534.0     1
10851.0    1
8500.0     1
4639.0     1
5363.0     1
4081.0     1
3578.0     1
17328.0    1
10793.0    1
17099.0    1
2519.0     1
6586.0     1
12808.0    1
4721.0     1
4615.0     1
16959.0    1
10306.0    1
5406.0     1
5902.0     1
10855.0    1
5914.0     1
6646.0     1
13973.0    1
13320.0    1
6687.0     1
4735.0     1
13872.0    1
5067.0     1
3692.0     1
19847.0    1
10475.0    1
10266.0    1
3210.0     1
19545.0    1
19232.0    1
17169.0    1
17174.0    1
16595.0    1
19973.0    1
13402.0    1
13206.0    1
18041.0    1
16064.0    1
19246.0    1
10748.0    1
16752.0    1
6201.0     1
19845.0    1
4001.0     1
10447.0    1
5747.0     1
10422.0    1
2348.0     1
19033.0    1
3407.0     1
2929.0     1
12031.0    1
15427.0    1
5126.0     1
9619.0     1
5010.0     1
10400.0    1
7083.0     1
2793.0     1
5674.0     1
19197.0    1
8412.0     1
3348.0     1
5309.0     1
7654.0     1
4723.0     1
7988.0     1
3072.0     1
7403.0     1
12490.0    1
8020.0     1
17068.0    1
8943.0     1
19272.0    1
5577.0     1
2691.0     1
8823.0     1
10008.0    1
3579.0     1
17779.0    1
18213.0    1
13577.0    1
19190.0    1
17123.0    1
19187.0    1
11878.0    1
8095.0     1
16856.0    1
9439.0     1
2532.0     1
5666.0     1
13726.0    1
4107.0     1
3597.0     1
4115.0     1
6272.0     1
2517.0     1
9204.0     1
4373.0     1
2064.0     1
2430.0     1
4877.0     1
2013.0     1
2974.0     1
2766.0     1
3377.0     1
4194.0     1
3424.0     1
6288.0     1
10496.0    1
3815.0     1
2389.0     1
4000.0     1
17584.0    1
5661.0     1
4869.0     1
4649.0     1
2768.0     1
6062.0     1
3408.0     1
3755.0     1
2187.0     1
4258.0     1
5326.0     1
5485.0     1
17639.0    1
4213.0     1
6513.0     1
4284.0     1
3212.0     1
2024.0     1
3058.0     1
3929.0     1
4425.0     1
2328.0     1
5940.0     1
2622.0     1
19999.0    1
10650.0    1
6931.0     1
2176.0     1
3230.0     1
18665.0    1
2789.0     1
11935.0    1
2546.0     1
4317.0     1
4739.0     1
2226.0     1
3944.0     1
5561.0     1
2897.0     1
5321.0     1
5410.0     1
4850.0     1
2001.0     1
4404.0     1
2960.0     1
18844.0    1
18947.0    1
6465.0     1
2683.0     1
2014.0     1
3441.0     1
13664.0    1
5021.0     1
5265.0     1
2774.0     1
4537.0     1
18172.0    1
6274.0     1
4381.0     1
2559.0     1
5488.0     1
2514.0     1
3196.0     1
4087.0     1
5368.0     1
12936.0    1
4221.0     1
4963.0     1
4200.0     1
5006.0     1
7639.0     1
6502.0     1
13525.0    1
6349.0     1
6180.0     1
3622.0     1
2725.0     1
14411.0    1
17924.0    1
4014.0     1
12742.0    1
3376.0     1
10482.0    1
4249.0     1
6549.0     1
19586.0    1
6397.0     1
8237.0     1
3211.0     1
16704.0    1
4774.0     1
4568.0     1
5993.0     1
6499.0     1
6380.0     1
3102.0     1
4556.0     1
5487.0     1
6842.0     1
3989.0     1
4930.0     1
3702.0     1
2705.0     1
4448.0     1
2379.0     1
2810.0     1
2141.0     1
8938.0     1
9936.0     1
5454.0     1
18740.0    1
5473.0     1
13503.0    1
13549.0    1
3936.0     1
4876.0     1
4230.0     1
4323.0     1
4859.0     1
6322.0     1
10761.0    1
2973.0     1
5204.0     1
17399.0    1
16885.0    1
5155.0     1
8853.0     1
2936.0     1
18789.0    1
4883.0     1
2029.0     1
2996.0     1
9278.0     1
4162.0     1
4447.0     1
Name: Monthly_Income, dtype: int64

In [14]:
num_duplicados_monthly = df.duplicated(subset=['Monthly_Income']).sum()
print(f"Número de filas duplicadas en 'Monthly_Income': {num_duplicados_monthly}")

Número de filas duplicadas en 'Monthly_Income': 808

In [19]:
# Verificar si hay valores nulos en la columna Monthly_Income
hay_nulos = df['Monthly_Income'].isnull().any()
print(f"¿Hay valores nulos en 'Monthly_Income'? {hay_nulos}")

¿Hay valores nulos en 'Monthly_Income'? True

In [20]:
# Contar el número de valores nulos en la columna Monthly_Income
num_nulos = df['Monthly_Income'].isnull().sum()
print(f"Número de valores nulos en 'Monthly_Income': {num_nulos}")

Número de valores nulos en 'Monthly_Income': 782

OVER_TIME

In [23]:
# Obtener un resumen estadístico de la columna Over_Time
df['Over_Time'].describe()

count       865
unique        2
top       False
freq        625
Name: Over_Time, dtype: object

In [21]:
valores_unicos_Over_time = df['Over_Time'].unique()
print("Valores únicos en la columna 'Over_Time':")
print(valores_unicos_Over_time)

Valores únicos en la columna 'Over_Time':
[False nan True]

In [24]:
# Contar valores nulos en la columna Over_Time
num_nulos = df['Over_Time'].isnull().sum()
print(f"\nNúmero de valores nulos en 'Over_Time': {num_nulos}")

# Ver los valores únicos y su frecuencia en la columna Over_Time
print("\nValores únicos y su frecuencia en 'Over_Time':")
valores_unicos = df['Over_Time'].value_counts()
print(valores_unicos)

Número de valores nulos en 'Over_Time': 612

Valores únicos y su frecuencia en 'Over_Time':
False    625
True     240
Name: Over_Time, dtype: int64